set -g mouse off


# Global Status Bar: Black text on White background
set -g status-style bg=white,fg=black
set -g status-position bottom

# Left Side: Session Name in pure black
set -g status-left-length 30
set -g status-left "#[fg=black][#S] #[default]"

# Right Side: Host and Time in pure black
set -g status-right-length 60
set -g status-right "#[fg=black]#h | %H:%M | %d-%b-%y"

# Window Tab Defaults (Inactive)
setw -g window-status-format " #I:#W#F "

# 1. Active Tab: Dark Green background, White text (No Bold)
setw -g window-status-current-style bg=colour28,fg=white,none
setw -g window-status-current-format " #I:#W#F "

# 2. Event/Activity Tab: Dark Red background, White text (No Bold)
setw -g monitor-activity on
set -g visual-activity off
setw -g window-status-activity-style bg=colour124,fg=white,none

# Switch window hotkeys (Alt/Option+Left/Right arrow)
bind -n M-Left select-window -t :-1
bind -n M-Right select-window -t :+1


# https://github.com/tmux-plugins/tmux-sensible
set -s escape-time 0
set -g history-limit 5000
set -g display-time 4000
set -g status-interval 5
set -g default-terminal "tmux-256color"
set -g status-keys emacs
set -g focus-events on
setw -g aggressive-resize on


# C-b -> C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix


# https://gist.github.com/sergebulaev/9be1b840e16501ab5f033cc57142f5de
set-option -sa terminal-overrides ",xterm*:Tc"
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on


# https://yazi-rs.github.io/docs/image-preview
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM


# https://hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/
set -g mouse off


# Some random Stackoverflow
bind-key -n S-Enter send-keys Escape "[13;2u"


# From pi
set -g extended-keys on
